// Generated by EnvQL. DO NOT EDIT MANUALLY.
declare global {
  namespace NodeJS {
    interface ProcessEnv {
      environment: string;
      port: number;
      database_url: string;
    }
  }
}

export {};
