# Generated by EnvQL. DO NOT EDIT MANUALLY.
from dataclasses import dataclass
from envql_secure import validate_and_load_secure

@dataclass(frozen=True)
class EnvConfig:
    environment: str
    port: int
    database_url: str

    @classmethod
    def load(cls, schema_path: str = "schema.envql.enc") -> "EnvConfig":
        config = validate_and_load_secure(schema_path)
        return cls(
            environment=config["environment"],
            port=config["port"],
            database_url=config["database_url"],
        )
