#!/usr/bin/env python3
import sys
import os
import subprocess
import argparse

# Asegurar soporte de caracteres UTF-8 / emojis en consolas de Windows
if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
        sys.stderr.reconfigure(encoding="utf-8")
    except Exception:
        pass

from envql_secure import parse_schema_line, validate_and_load_secure, EnvQLError


def read_schema_lines(schema_path="schema.envql", enc_schema_path="schema.envql.enc"):
    """Lee las líneas del esquema desde el archivo plano o desde el cifrado."""
    if os.path.exists(schema_path):
        with open(schema_path, "r", encoding="utf-8") as f:
            return f.read().splitlines()
    elif os.path.exists(enc_schema_path):
        from envql_secure import decrypt_and_read_schema
        return decrypt_and_read_schema(enc_schema_path)
    else:
        raise EnvQLError(f"❌ No se encontró '{schema_path}' ni '{enc_schema_path}'. Ejecuta 'envql init'.")


def generate_typescript_types(output_path="env.d.ts", schema_path="schema.envql"):
    """Genera definiciones de tipos de TypeScript (env.d.ts)."""
    lines = read_schema_lines(schema_path)
    type_map = {
        "String": "string",
        "Int": "number",
        "Boolean": "boolean"
    }

    ts_fields = []
    for line in lines:
        parsed = parse_schema_line(line)
        if not parsed:
            continue
        key = parsed["key"]
        vtype = parsed["type"]
        ts_type = type_map.get(vtype, "string")
        ts_fields.append(f"      {key}: {ts_type};")

    fields_str = "\n".join(ts_fields)
    content = f"""// Generated by EnvQL. DO NOT EDIT MANUALLY.
declare global {{
  namespace NodeJS {{
    interface ProcessEnv {{
{fields_str}
    }}
  }}
}}

export {{}};
"""
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"⚡ [EnvQL DX] Tipos TypeScript generados exitosamente en: '{output_path}'")


def generate_python_types(output_path="env_config.py", schema_path="schema.envql"):
    """Genera una clase dataclass tipada para Python (env_config.py)."""
    lines = read_schema_lines(schema_path)
    type_map = {
        "String": "str",
        "Int": "int",
        "Boolean": "bool"
    }

    py_fields = []
    py_inits = []
    for line in lines:
        parsed = parse_schema_line(line)
        if not parsed:
            continue
        key = parsed["key"]
        vtype = parsed["type"]
        py_type = type_map.get(vtype, "str")
        py_fields.append(f"    {key}: {py_type}")
        py_inits.append(f'            {key}=config["{key}"],')

    fields_str = "\n".join(py_fields)
    inits_str = "\n".join(py_inits)

    content = f'''# Generated by EnvQL. DO NOT EDIT MANUALLY.
from dataclasses import dataclass
from envql_secure import validate_and_load_secure

@dataclass(frozen=True)
class EnvConfig:
{fields_str}

    @classmethod
    def load(cls, schema_path: str = "schema.envql.enc") -> "EnvConfig":
        config = validate_and_load_secure(schema_path)
        return cls(
{inits_str}
        )
'''
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(content)
    print(f"⚡ [EnvQL DX] Clase tipada de Python generada exitosamente en: '{output_path}'")


def main():
    parser = argparse.ArgumentParser(description="EnvQL CLI: El estándar universal para configuración y secretos.")
    subparsers = parser.add_subparsers(dest="command", help="Comandos disponibles")

    # init
    subparsers.add_parser("init", help="Inicializa un nuevo schema.envql en el proyecto")

    # key:generate
    subparsers.add_parser("key:generate", help="Genera una llave maestra simétrica (envql.key)")

    # encrypt
    encrypt_parser = subparsers.add_parser("encrypt", help="Cifra un archivo de esquema plano")
    encrypt_parser.add_argument("--input", default="schema.envql", help="Archivo de esquema de entrada")
    encrypt_parser.add_argument("--output", default="schema.envql.enc", help="Archivo cifrado de salida")

    # generate
    gen_parser = subparsers.add_parser("generate", help="Genera tipos para IDEs (TypeScript / Python)")
    gen_parser.add_argument("--target", choices=["typescript", "python"], required=True, help="Lenguaje objetivo")
    gen_parser.add_argument("--schema", default="schema.envql", help="Ruta al archivo schema")
    gen_parser.add_argument("--output", default=None, help="Ruta personalizada para el archivo generado")

    # run
    run_parser = subparsers.add_parser("run", help="Valida el entorno y ejecuta el comando de la aplicación")
    run_parser.add_argument("--schema", default="schema.envql.enc", help="Archivo de esquema cifrado a validar")
    run_parser.add_argument("cmd", nargs=argparse.REMAINDER, help="Comando a ejecutar tras validar")

    args = parser.parse_args()

    if args.command == "init":
        print("🚀 Inicializando archivo schema.envql en el directorio actual...")
        with open("schema.envql", "w", encoding="utf-8") as f:
            f.write("# schema.envql - Definición de Entorno\nenvironment: String @default(\"development\")\nport: Int @default(3000)\ndatabase_url: String @secret\n")
        print("✨ ¡Creado con éxito: schema.envql!")

    elif args.command == "key:generate":
        print("🔑 Generando llave maestra envql.key...")
        from cryptography.fernet import Fernet
        key = Fernet.generate_key()
        with open("envql.key", "wb") as kf:
            kf.write(key)
        print("✨ ¡Llave maestra generada con éxito! No la compartas ni la subas a Git.")

    elif args.command == "encrypt":
        from cryptography.fernet import Fernet
        key_path = "envql.key"
        if not os.path.exists(key_path):
            print(f"❌ Error: No se encontró la llave maestra '{key_path}'. Ejecuta 'key:generate' primero.")
            sys.exit(1)
        with open(key_path, "rb") as kf:
            key = kf.read()
        f = Fernet(key)
        if not os.path.exists(args.input):
            print(f"❌ Error: No se encontró el archivo de entrada '{args.input}'.")
            sys.exit(1)
        with open(args.input, "rb") as file:
            data = file.read()
        enc_data = f.encrypt(data)
        with open(args.output, "wb") as file:
            file.write(enc_data)
        print(f"🔒 [EnvQL Security] Archivo cifrado con éxito: '{args.output}'")

    elif args.command == "generate":
        try:
            if args.target == "typescript":
                out = args.output or "env.d.ts"
                generate_typescript_types(output_path=out, schema_path=args.schema)
            elif args.target == "python":
                out = args.output or "env_config.py"
                generate_python_types(output_path=out, schema_path=args.schema)
        except Exception as e:
            print(f"❌ Error al generar tipos: {e}")
            sys.exit(1)

    elif args.command == "run":
        if not args.cmd:
            print("❌ Error: Debes especificar el comando que deseas ejecutar. Ejemplo: python envql_cli.py run python app.py")
            sys.exit(1)

        print("🛡️ [EnvQL Runtime] Validando entorno antes de arrancar...")
        try:
            validated_env = validate_and_load_secure(args.schema)
        except EnvQLError as e:
            print(f"{e}")
            print("🚫 Abortando ejecución debido a fallo en validación de entorno.")
            sys.exit(1)

        # Inyectar las variables validadas en el entorno del proceso hijo
        env_vars = os.environ.copy()
        for k, v in validated_env.items():
            env_vars[k.upper()] = str(v)

        print(f"🚀 Ejecutando comando: {' '.join(args.cmd)}")
        result = subprocess.run(args.cmd, env=env_vars)
        sys.exit(result.returncode)

    else:
        parser.print_help()


if __name__ == "__main__":
    main()
